---
chrony_network: '{{ subnet }}'
ocp_version: 4.12
ocp_installer: "openshift-install-linux-4.12.0.tar.gz"
ocp_installer_url: "https://mirror.openshift.com/pub/openshift-v4/ppc64le/clients/ocp/4.12.0/openshift-install-linux-4.12.0.tar.gz"
ocp_client_url: "https://mirror.openshift.com/pub/openshift-v4/ppc64le/clients/ocp/4.12.0/openshift-client-linux-4.12.0.tar.gz"
ocp_installer_gzip: "openshift-install-linux-4.12.0.tar.gz"
ocp_client_gzip: "openshift-client-linux-4.12.0.tar.gz"
ocp_master_count: 3
ocp_pull_secret: ''

ocp_public_ssh_key: '{{ root_rsa_pub }}'


